"""empty message

Revision ID: 4e4cbf5c8e3c
Revises: 
Create Date: 2020-01-05 21:12:31.382770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4cbf5c8e3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('book_name', sa.String(length=64), nullable=True),
    sa.Column('book_url', sa.String(length=128), nullable=True),
    sa.Column('book_img', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('style', sa.String(length=64), nullable=True),
    sa.Column('last_update_url', sa.String(length=128), nullable=True),
    sa.Column('last_update_name', sa.String(length=64), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('chapter_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_book_name'), 'novels', ['book_name'], unique=False)
    op.create_index(op.f('ix_novels_last_update_name'), 'novels', ['last_update_name'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_name', sa.String(length=64), nullable=True),
    sa.Column('chapter_url', sa.String(length=128), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('chapter_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_chapter_url'), 'chapters', ['chapter_url'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_index(op.f('ix_chapters_chapter_url'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_last_update_name'), table_name='novels')
    op.drop_index(op.f('ix_novels_book_name'), table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
